services:
  nginx:
    image: ghcr.io/jimmymsh/jimmymishan.com/site:${TAG:-latest}
    restart: always
    cgroup_parent: nginx
    ports:
      - "80:80"
      - "443:443"
    environment:
      - CERTBOT_EMAIL=${CERTBOT_EMAIL}
    volumes:
      - nginx_secrets:/etc/letsencrypt
    depends_on:
      api:
        condition: service_healthy
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "3"

  api:
    image: ghcr.io/jimmymsh/jimmymishan.com/api:${TAG:-latest}
    restart: always
    cgroup_parent: api
    env_file:
      - .env
    volumes:
      - ./data:/data
      - /sys/fs/cgroup:/host/cgroup:ro
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "3"

  goatcounter:
    image: arp242/goatcounter:2.7.0
    restart: always
    command:
      - serve
      - -listen=:8080
      - -tls=http
      - -automigrate
      - -db=sqlite+/home/goatcounter/goatcounter-data/goatcounter.db
    cgroup_parent: goatcounter
    volumes:
      - ./data/goatcounter:/home/goatcounter/goatcounter-data
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "3"

volumes:
  nginx_secrets:
