services:
  nginx:
    build:
      context: .
      dockerfile: docker/site.Dockerfile
      target: local
    cgroup_parent: nginx
    ports:
      - "8080:80"
      - "8443:443"
    depends_on:
      - api
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "3"

  api:
    build:
      context: .
      dockerfile: docker/api.Dockerfile
    cgroup_parent: api
    environment:
      - LOG_TAIL_ALLOW_PRIVATE=true
    volumes:
      - ./data:/data
      - /sys/fs/cgroup:/host/cgroup:ro
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "3"
